#!/usr/bin/env python3
"""
Architecture documentation text generator for Mermaid diagrams.
"""
from typing import Dict, Any
from sprint1.src.diagram_generator import system_diagram, sequence_diagram, er_diagram

def generate_architecture_doc(report: Dict[str, Any]) -> str:
    context = report.get("context", {})
    repository = context.get("repository", "Unknown Repository")
    branch = context.get("branch", "main")
    commit = context.get("commit_sha", "unknown")
    
    # Generate the diagrams to embed them directly
    sys_diag = system_diagram(report)
    seq_diag = sequence_diagram(report)
    er_diag = er_diagram(report)

    doc = f"""# System Architecture Documentation

**Repository**: `{repository}`
**Branch**: `{branch}`
**Snapshot Commit**: `{commit}`

---

## 1. Executive Overview

This document provides a comprehensive architectural overview of the software system. 
It captures the structural components, interaction flows, and data models inferred from the codebase. 
The architecture is designed to support scalable business operations while maintaining strict separation of concerns.

## 2. System Context

The System Diagram below visualizes the high-level architecture, identifying key components in the Client, Server, and Infrastructure layers.

### System Diagram

```mermaid
{sys_diag}
```

**Architectural Highlights:**
- **Client Layer**: Responsible for user interaction and presentation logic.
- **Server Layer**: API Gateway and Service modules managing business logic and security (Auth).
- **Infrastructure Layer**: Persistent storage (Database), Caching (Redis), and Async Messaging (Queues) where applicable.

---

## 3. Interaction Flow

The Sequence Diagram illustrates the typical request lifecycle, demonstrating how data flows from the user, through the API, to the backing services.

### Core Request Flow

```mermaid
{seq_diag}
```

**Flow Analysis:**
1. **Secure Access**: Requests are validated via Authentication modules before processing.
2. **Optimization**: Caching mechanisms are employed to reduce database load for read-heavy operations.
3. **Asynchronous Processing**: Long-running tasks are offloaded to background workers to ensure responsive APIs.

---

## 4. Data Model

The Entity-Relationship (ER) diagram represents the domain model and its persistence structure.

### Domain Entities

```mermaid
{er_diag}
```

**Key Data Structures:**
- **Core Entities**: Represents the primary business objects (e.g., User, Project, Resource).
- **Relationships**: Defines the cardinality and dependencies between data models.

---

*This live documentation was automatically generated by the Architecture Analysis Engine.*
"""
    return doc


