#!/usr/bin/env python3
"""
README Generator
Creates comprehensive auto-generated README documentation
"""
from datetime import datetime

def generate_readme(report):
    """
    Generate README from impact report
    
    Args:
        report (dict): Impact report from EPIC-1
    
    Returns:
        str: Formatted README content
    """
    context = report.get("context", {})
    analysis = report.get("analysis_summary", {})
    changes = report.get("changes", [])
    
    repository = context.get("repository", "Unknown Repository")
    branch = context.get("branch", "main")
    commit = context.get("commit_sha", "unknown")
    author = context.get("author", "Unknown")
    severity = analysis.get("highest_severity", "UNKNOWN")
    breaking = analysis.get("breaking_changes_detected", False)
    
    # Count changes by language
    languages = {}
    for change in changes:
        lang = change.get("language", "unknown")
        languages[lang] = languages.get(lang, 0) + 1
    
    # Build README content
    readme = f"""# {repository}

## 📋 Auto-Generated Documentation

This documentation was automatically generated based on code analysis and changes.

**Generated:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC

---

## 📊 Repository Information

| Attribute | Value |
|-----------|-------|
| **Repository** | `{repository}` |
| **Branch** | `{branch}` |
| **Commit** | `{commit}` |
| **Author** | `{author}` |
| **Severity** | `{severity}` |
| **Breaking Changes** | {'⚠️ Yes' if breaking else '✅ No'} |

---

## 📁 Changed Files

**Total Files Changed:** {len(changes)}

"""
    
    # Add language breakdown if available
    if languages:
        readme += "### By Language\n\n"
        for lang, count in sorted(languages.items()):
            readme += f"- **{lang.capitalize()}**: {count} file(s)\n"
        readme += "\n"
    
    # List changed files
    if changes:
        readme += "### File List\n\n"
        for i, change in enumerate(changes, 1):
            file_path = change.get("file", "unknown")
            readme += f"{i}. `{file_path}`\n"
        readme += "\n"
    
    # Add severity information
    readme += f"""---

## ⚠️ Change Impact

**Severity Level:** `{severity}`

"""
    
    if severity == "CRITICAL":
        readme += "🔴 **CRITICAL** - Requires immediate attention. These changes may have significant system-wide impact.\n"
    elif severity == "MAJOR":
        readme += "🟠 **MAJOR** - Important changes that may affect multiple components.\n"
    elif severity == "MINOR":
        readme += "🟡 **MINOR** - Routine changes with limited scope.\n"
    else:
        readme += "🟢 **LOW** - Minor changes with minimal impact.\n"
    
    readme += f"""
**Breaking Changes:** {'Yes - Review carefully before deployment' if breaking else 'None detected'}

---

## 📚 Additional Documentation

- [API Reference](api/api-reference.md)
- [Architecture Decision Records](adr/ADR-001.md)
- [System Diagrams](architecture/)

---

## 🤖 About This Document

This README was automatically generated by the EPIC-2 documentation pipeline based on code analysis from EPIC-1.

For more information about the documentation system, see the [documentation snapshot](doc_snapshot.json).
"""
    
    return readme