#!/usr/bin/env python3
"""
README Generator
Creates comprehensive auto-generated README documentation
"""
from sprint1.src.narrative_generator import generate_readme_narrative, generate_impact_narrative


def generate_readme(report, generated_at=None, rag_context=None):
    """
    Generate README from impact report
    
    Args:
        report (dict): Impact report from EPIC-1
    
    Returns:
        str: Formatted README content
    """
    context = report.get("context", {})
    analysis = report.get("analysis_summary", {})
    changes = report.get("changes", [])
    
    repository = context.get("repository", "Unknown Repository")
    branch = context.get("branch", "main")
    commit = context.get("commit_sha", "unknown")
    author = context.get("author", "Unknown")
    severity = analysis.get("highest_severity", "UNKNOWN")
    breaking = analysis.get("breaking_changes_detected", False)
    
    # Count changes by language, handling None values
    languages = {}
    for change in changes:
        lang = change.get("language")
        # Normalize None/null to "other"
        lang_key = lang if lang else "other"
        languages[lang_key] = languages.get(lang_key, 0) + 1
    
    rag_context = rag_context or {}
    overview = generate_readme_narrative(report, rag_context)
    impact_summary = generate_impact_narrative(report)

    # Build README content
    generated_at_str = generated_at or "unknown"
    readme = f"""# {repository}

## Auto-Generated Documentation

This documentation was automatically generated from the impact report and code changes.

{overview}

**Generated:** {generated_at_str}

---

## Repository Information

| Attribute | Value |
|-----------|-------|
| **Repository** | `{repository}` |
| **Branch** | `{branch}` |
| **Commit** | `{commit}` |
| **Author** | `{author}` |
| **Severity** | `{severity}` |
| **Breaking Changes** | {'Yes' if breaking else 'No'} |

---

## Changed Files

**Total Files Changed:** {len(changes)}

"""
    
    # Add language breakdown if available
    if languages:
        readme += "### By Language\n\n"
        # Sort by language name, handling the case where language is "other"
        for lang, count in sorted(languages.items(), key=lambda x: (x[0] == "other", x[0])):
            display_name = lang.capitalize() if lang != "other" else "Other/Unknown"
            readme += f"- **{display_name}**: {count} file(s)\n"
        readme += "\n"
    
    # List changed files
    if changes:
        readme += "### File List\n\n"
        for i, change in enumerate(changes, 1):
            file_path = change.get("file", "unknown")
            readme += f"{i}. `{file_path}`\n"
        readme += "\n"
    
    # Add severity information
    readme += f"""---

## Change Impact

**Severity Level:** `{severity}`

"""
    
    if severity == "CRITICAL":
        readme += "**CRITICAL** - Requires immediate attention. These changes may have significant system-wide impact.\n"
    elif severity == "MAJOR":
        readme += "**MAJOR** - Important changes that may affect multiple components.\n"
    elif severity == "MINOR":
        readme += "**MINOR** - Routine changes with limited scope.\n"
    else:
        readme += "**LOW** - Minor changes with minimal impact.\n"
    
    readme += f"""
**Breaking Changes:** {'Yes - Review carefully before deployment' if breaking else 'None detected'}

{impact_summary}

---

## Additional Documentation

- [API Reference](api/api-reference.md)
- [Architecture Decision Records](adr/ADR-001.md)
- [System Diagrams](architecture/)

---

## Installation

Not detected in the impact report.

## Usage

Not detected in the impact report.

## Features

Not detected in the impact report.

## Tech Stack

Not detected in the impact report.

## Configuration

Not detected in the impact report.

## Troubleshooting

Not detected in the impact report.

## Contributing

Not detected in the impact report.

## License

Not detected in the impact report.

---

## About This Document

This README was automatically generated by the EPIC-2 documentation pipeline based on the impact report.

For more information about the documentation system, see the [documentation snapshot](doc_snapshot.json).
"""
    
    return readme
