import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import { fetchProjects, createProject, clearError } from '../store/slices/projectsSlice'
import Navbar from '../components/Navbar'

const Projects = () => {
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const { projects, isLoading, error } = useAppSelector((state) => state.projects)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    githubUrl: '',
    autoGenerateDocs: false,
    githubAccessToken: '',
  })
  const [showToken, setShowToken] = useState(false)
  const [formError, setFormError] = useState('')

  useEffect(() => {
    dispatch(fetchProjects())
  }, [dispatch])

  useEffect(() => {
    dispatch(clearError())
  }, [dispatch])

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target
    if (type === 'checkbox') {
      setFormData((prev) => ({ ...prev, [name]: (e.target as HTMLInputElement).checked }))
    } else {
      setFormData((prev) => ({ ...prev, [name]: value }))
    }
  }

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault()
    setFormError('')

    if (!formData.name.trim()) {
      setFormError('Project name is required')
      return
    }

    if (!formData.githubUrl.trim()) {
      setFormError('GitHub URL is required')
      return
    }

    // Validate GitHub URL format
    try {
      new URL(formData.githubUrl)
    } catch {
      setFormError('Please enter a valid GitHub URL')
      return
    }

    const payload = {
      name: formData.name,
      description: formData.description || undefined,
      githubUrl: formData.githubUrl,
      autoGenerateDocs: formData.autoGenerateDocs,
      githubAccessToken: formData.githubAccessToken || undefined,
    }

    const result = await dispatch(createProject(payload))
    if (createProject.fulfilled.match(result)) {
      setShowCreateModal(false)
      setFormData({ name: '', description: '', githubUrl: '', autoGenerateDocs: false, githubAccessToken: '' })
      setShowToken(false)
      navigate(`/projects/${result.payload.id}`)
    }
  }

  const closeModal = () => {
    setShowCreateModal(false)
    setFormData({ name: '', description: '', githubUrl: '', autoGenerateDocs: false, githubAccessToken: '' })
    setShowToken(false)
    setFormError('')
  }

  return (
    <div className="page-container">
      <Navbar />
      <main className="main-content">
        <div className="content-header">
          <h1>Projects</h1>
          <button className="btn btn-primary" onClick={() => setShowCreateModal(true)}>
            + New Project
          </button>
        </div>

        {error && <div className="alert alert-error">{error}</div>}

        {isLoading ? (
          <div className="loading">Loading projects...</div>
        ) : projects.length === 0 ? (
          <div className="empty-state">
            <h2>No projects yet</h2>
            <p>Create your first project to get started</p>
            <button className="btn btn-primary" onClick={() => setShowCreateModal(true)}>
              Create Project
            </button>
          </div>
        ) : (
          <div className="projects-grid">
            {projects.map((project) => (
              <Link to={`/projects/${project.id}`} key={project.id} className="project-card">
                <div className="project-card-header">
                  <h3>{project.name}</h3>
                  <span className={`role-badge role-${project.memberRole}`}>
                    {project.memberRole}
                  </span>
                </div>
                {project.description && (
                  <p className="project-description">{project.description}</p>
                )}
                {project.githubUrl && (
                  <div className="project-github">
                    <span>GitHub</span>
                  </div>
                )}
                <div className="project-meta">
                  <span>Created {new Date(project.createdAt).toLocaleDateString()}</span>
                </div>
              </Link>
            ))}
          </div>
        )}

        {/* Create Project Modal */}
        {showCreateModal && (
          <div className="modal-overlay" onClick={closeModal}>
            <div className="modal modal-large" onClick={(e) => e.stopPropagation()}>
              <div className="modal-header">
                <h2>Create New Project</h2>
                <button className="btn-close" onClick={closeModal}>×</button>
              </div>
              <form onSubmit={handleCreateProject}>
                <div className="form-group">
                  <label htmlFor="name">Project Name *</label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    value={formData.name}
                    onChange={handleChange}
                    placeholder="My Awesome Project"
                    autoFocus
                  />
                </div>
                <div className="form-group">
                  <label htmlFor="description">Description</label>
                  <textarea
                    id="description"
                    name="description"
                    value={formData.description}
                    onChange={handleChange}
                    placeholder="What is this project about?"
                    rows={3}
                  />
                </div>
                <div className="form-group">
                  <label htmlFor="githubUrl">GitHub URL *</label>
                  <input
                    type="url"
                    id="githubUrl"
                    name="githubUrl"
                    value={formData.githubUrl}
                    onChange={handleChange}
                    placeholder="https://github.com/username/repo"
                    required
                  />
                  <small className="form-hint">Cannot be changed after project creation</small>
                </div>

                <div className="form-section">
                  <h3>Documentation Settings</h3>
                  
                  <div className="form-group-inline">
                    <label className="checkbox-label">
                      <input
                        type="checkbox"
                        name="autoGenerateDocs"
                        checked={formData.autoGenerateDocs}
                        onChange={handleChange}
                      />
                      <span>Auto-generate Documentation</span>
                    </label>
                    <small className="form-hint">Automatically generate docs when code changes are pushed</small>
                  </div>

                  <div className="form-group">
                    <label htmlFor="githubAccessToken">GitHub Access Token (optional)</label>
                    <div className="token-input-wrapper">
                      <input
                        type={showToken ? 'text' : 'password'}
                        id="githubAccessToken"
                        name="githubAccessToken"
                        value={formData.githubAccessToken}
                        onChange={handleChange}
                        placeholder="ghp_xxxxxxxxxxxx"
                        className="token-input"
                      />
                      <button
                        type="button"
                        className="btn-toggle-visibility"
                        onClick={() => setShowToken(!showToken)}
                      >
                        {showToken ? 'Hide' : 'Show'}
                      </button>
                    </div>
                    <small className="form-hint">Required for private repositories and auto-generation</small>
                  </div>
                </div>

                {formError && <div className="alert alert-error">{formError}</div>}
                {error && <div className="alert alert-error">{error}</div>}
                <div className="modal-actions">
                  <button type="button" className="btn btn-secondary" onClick={closeModal}>
                    Cancel
                  </button>
                  <button type="submit" className="btn btn-primary" disabled={isLoading}>
                    {isLoading ? 'Creating...' : 'Create Project'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

export default Projects
