import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import {
  fetchProjectById,
  updateProject,
  deleteProject,
  updateProjectSettings,
  inviteMember,
  cancelInvitation,
  removeMember,
  updateMemberRole,
  clearCurrentProject,
  clearError,
} from '../store/slices/projectsSlice'
import { projectsApi } from '../services/api'
import Navbar from '../components/Navbar'
import DocumentList from '../components/DocumentList'
import AppThreeBackground from '../components/AppThreeBackground'

const ProjectDetail = () => {
  const { id } = useParams<{ id: string }>()
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const { currentProject, isLoading, error } = useAppSelector((state) => state.projects)
  const { user } = useAppSelector((state) => state.auth)

  const [activeTab, setActiveTab] = useState<'overview' | 'documents' | 'members' | 'settings'>('overview')
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState({
    name: '',
    description: '',
  })
  const [inviteEmail, setInviteEmail] = useState('')
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [inviteError, setInviteError] = useState('')

  // Settings state
  const [autoGenerateDocs, setAutoGenerateDocs] = useState(false)
  const [githubToken, setGithubToken] = useState('')
  const [showGithubToken, setShowGithubToken] = useState(false)
  const [settingsLoading, setSettingsLoading] = useState(false)
  const [docGenLoading, setDocGenLoading] = useState(false)
  const [docGenMessage, setDocGenMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)

  useEffect(() => {
    if (id) {
      dispatch(fetchProjectById(id))
    }
    return () => {
      dispatch(clearCurrentProject())
    }
  }, [dispatch, id])

  useEffect(() => {
    if (currentProject) {
      setEditForm({
        name: currentProject.name,
        description: currentProject.description || '',
      })
      // Set settings state
      setAutoGenerateDocs(currentProject.settings?.autoGenerateDocs || false)
      // Don't set the token - we never receive it from the server
      setGithubToken('')
    }
  }, [currentProject])

  useEffect(() => {
    dispatch(clearError())
  }, [dispatch])

  const canManageProject = currentProject?.memberRole === 'owner' || currentProject?.memberRole === 'admin'
  const isOwner = currentProject?.memberRole === 'owner'
  const totalMembers = currentProject?.members?.length || 0
  const pendingInvites = currentProject?.pendingInvitations?.length || 0
  const createdAtLabel = currentProject ? new Date(currentProject.createdAt).toLocaleString() : ''
  const updatedAtLabel = currentProject ? new Date(currentProject.updatedAt).toLocaleString() : ''

  const handleEditChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target
    setEditForm((prev) => ({ ...prev, [name]: value }))
  }

  const handleSaveChanges = async () => {
    if (!id || !editForm.name.trim()) return

    const result = await dispatch(updateProject({ id, data: editForm }))
    if (updateProject.fulfilled.match(result)) {
      setIsEditing(false)
    }
  }

  const handleDelete = async () => {
    if (!id) return

    const result = await dispatch(deleteProject(id))
    if (deleteProject.fulfilled.match(result)) {
      navigate('/projects')
    }
  }

  const handleInvite = async (e: React.FormEvent) => {
    e.preventDefault()
    setInviteError('')

    if (!id || !inviteEmail.trim()) {
      setInviteError('Email is required')
      return
    }

    const result = await dispatch(inviteMember({ projectId: id, email: inviteEmail }))
    if (inviteMember.fulfilled.match(result)) {
      setInviteEmail('')
    } else if (inviteMember.rejected.match(result)) {
      setInviteError(result.payload as string)
    }
  }

  const handleCancelInvitation = async (invitationId: string) => {
    if (!id) return
    await dispatch(cancelInvitation({ projectId: id, invitationId }))
  }

  const handleRemoveMember = async (memberId: string) => {
    if (!id) return
    await dispatch(removeMember({ projectId: id, memberId }))
  }

  const handleChangeRole = async (memberId: string, newRole: string) => {
    if (!id) return
    await dispatch(updateMemberRole({ projectId: id, memberId, role: newRole }))
  }

  const handleToggleAutoGenerate = async () => {
    if (!id) return
    setSettingsLoading(true)
    const newValue = !autoGenerateDocs
    const result = await dispatch(updateProjectSettings({ id, data: { autoGenerateDocs: newValue } }))
    if (updateProjectSettings.fulfilled.match(result)) {
      setAutoGenerateDocs(newValue)
    }
    setSettingsLoading(false)
  }

  const handleSaveGithubToken = async () => {
    if (!id) return
    setSettingsLoading(true)
    await dispatch(updateProjectSettings({ id, data: { githubAccessToken: githubToken || null } }))
    setSettingsLoading(false)
    setGithubToken('')
    setShowGithubToken(false)
  }

  const handleClearGithubToken = async () => {
    if (!id) return
    setSettingsLoading(true)
    await dispatch(updateProjectSettings({ id, data: { githubAccessToken: null } }))
    setSettingsLoading(false)
  }

  const handleTriggerDocGeneration = async () => {
    if (!id) return
    setDocGenLoading(true)
    setDocGenMessage(null)
    try {
      await projectsApi.triggerDocGeneration(id)
      setDocGenMessage({ type: 'success', text: 'Documentation generation started! This may take a few minutes.' })
    } catch (err: any) {
      setDocGenMessage({ type: 'error', text: err.response?.data?.detail || 'Failed to trigger documentation generation' })
    } finally {
      setDocGenLoading(false)
    }
  }

  if (isLoading && !currentProject) {
    return (
      <div className="page-container">
        <Navbar />
        <main className="main-content">
          <div className="loading">Loading project...</div>
        </main>
      </div>
    )
  }

  if (!currentProject) {
    return (
      <div className="page-container">
        <Navbar />
        <main className="main-content">
          <div className="error-state">
            <h2>Project not found</h2>
            <button className="btn btn-primary" onClick={() => navigate('/projects')}>
              Back to Projects
            </button>
          </div>
        </main>
      </div>
    )
  }

  return (
    <div className="page-container project-detail-shell">
      <AppThreeBackground variant="detail" />
      <Navbar />
      <main className="main-content">
        <div className="content-header">
          <div className="breadcrumb">
            <button className="btn-link" onClick={() => navigate('/projects')}>
              Projects
            </button>
            <span>/</span>
            <span>{currentProject.name}</span>
          </div>
        </div>

        {error && <div className="alert alert-error">{error}</div>}

        {/* Tabs */}
        <div className="tabs">
          <button
            className={`tab ${activeTab === 'overview' ? 'active' : ''}`}
            onClick={() => setActiveTab('overview')}
          >
            Overview
          </button>
          <button
            className={`tab ${activeTab === 'documents' ? 'active' : ''}`}
            onClick={() => setActiveTab('documents')}
          >
            Documents
          </button>
          <button
            className={`tab ${activeTab === 'members' ? 'active' : ''}`}
            onClick={() => setActiveTab('members')}
          >
            Members
          </button>
          {canManageProject && (
            <button
              className={`tab ${activeTab === 'settings' ? 'active' : ''}`}
              onClick={() => setActiveTab('settings')}
            >
              Settings
            </button>
          )}
        </div>

        {/* Overview Tab */}
        {activeTab === 'overview' && (
          <div className="tab-content">
            <div className="project-overview-grid">
              <section className="project-info-card project-overview-hero">
                <p className="project-overview-kicker">Project Overview</p>
                <h2>{currentProject.name}</h2>
                <div className="project-overview-role-wrap">
                  <span className={`role-badge role-${currentProject.memberRole}`}>
                    {currentProject.memberRole}
                  </span>
                </div>
                <p className="project-description-full">
                  {currentProject.description || 'No project description provided yet. Add one from Settings to help your team understand this workspace.'}
                </p>

                <div className="project-overview-actions">
                  <button className="btn btn-primary" onClick={() => setActiveTab('documents')}>
                    Open Documents
                  </button>
                  {currentProject.githubUrl ? (
                    <a className="btn btn-secondary" href={currentProject.githubUrl} target="_blank" rel="noopener noreferrer">
                      View on GitHub
                    </a>
                  ) : (
                    <button className="btn btn-secondary" disabled>
                      GitHub URL not set
                    </button>
                  )}
                </div>
              </section>

              <aside className="project-overview-side">
                <div className="project-overview-stats">
                  <div className="project-overview-stat">
                    <span>Members</span>
                    <strong>{totalMembers}</strong>
                  </div>
                  <div className="project-overview-stat">
                    <span>Pending Invites</span>
                    <strong>{pendingInvites}</strong>
                  </div>
                  <div className="project-overview-stat">
                    <span>Auto Docs</span>
                    <strong>{currentProject?.settings?.autoGenerateDocs ? 'On' : 'Off'}</strong>
                  </div>
                  <div className="project-overview-stat">
                    <span>GitHub Token</span>
                    <strong>{currentProject?.settings?.hasGithubToken ? 'Configured' : 'Missing'}</strong>
                  </div>
                </div>

                <div className="project-overview-timeline">
                  <h3>Timeline</h3>
                  <p>Created: {createdAtLabel}</p>
                  <p>Updated: {updatedAtLabel}</p>
                </div>
              </aside>
            </div>

            {currentProject.githubUrl && (
              <div className="project-overview-repo-card">
                <p className="project-overview-repo-label">Repository</p>
                <a href={currentProject.githubUrl} target="_blank" rel="noopener noreferrer">
                  {currentProject.githubUrl}
                </a>
              </div>
            )}
          </div>
        )}

        {/* Documents Tab */}
        {activeTab === 'documents' && (
          <div className="tab-content">
            <DocumentList
              projectId={currentProject.id}
              canManage={canManageProject}
            />
          </div>
        )}

        {/* Members Tab */}
        {activeTab === 'members' && (
          <div className="tab-content">
            {/* Invite Member Form */}
            {canManageProject && (
              <div className="invite-section">
                <h3>Invite Member</h3>
                <form onSubmit={handleInvite} className="invite-form">
                  <input
                    type="email"
                    value={inviteEmail}
                    onChange={(e) => setInviteEmail(e.target.value)}
                    placeholder="Enter email address"
                    className="invite-input"
                  />
                  <button type="submit" className="btn btn-primary" disabled={isLoading}>
                    Send Invite
                  </button>
                </form>
                {inviteError && <div className="alert alert-error">{inviteError}</div>}
              </div>
            )}

            {/* Current Members */}
            <div className="members-section">
              <h3>Members ({currentProject.members?.length || 0})</h3>
              <div className="members-list">
                {currentProject.members?.map((member) => (
                  <div key={member.id} className="member-item">
                    <div className="member-info">
                      <span className="member-name">{member.username}</span>
                      <span className="member-email">{member.email}</span>
                    </div>
                    {canManageProject && member.userId !== user?.id ? (
                      <div className="flex items-center gap-3">
                        <select
                          value={member.role}
                          onChange={(e) => handleChangeRole(member.id, e.target.value)}
                          className="role-select"
                          disabled={isLoading}
                        >
                          <option value="member">Member</option>
                          <option value="admin">Admin</option>
                          {isOwner && <option value="owner">Owner</option>}
                        </select>
                        {member.role !== 'owner' && (
                          <button
                            className="btn btn-danger btn-sm"
                            onClick={() => handleRemoveMember(member.id)}
                          >
                            Remove
                          </button>
                        )}
                      </div>
                    ) : (
                      <span className={`role-badge role-${member.role}`}>{member.role}</span>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Pending Invitations */}
            {canManageProject && currentProject.pendingInvitations && currentProject.pendingInvitations.length > 0 && (
              <div className="invitations-section">
                <h3>Pending Invitations</h3>
                <div className="invitations-list">
                  {currentProject.pendingInvitations.map((invitation) => (
                    <div key={invitation.id} className="invitation-item">
                      <span className="invitation-email">{invitation.email}</span>
                      <span className="invitation-status">Pending</span>
                      <button
                        className="btn btn-secondary btn-sm"
                        onClick={() => handleCancelInvitation(invitation.id)}
                      >
                        Cancel
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Settings Tab */}
        {activeTab === 'settings' && canManageProject && (
          <div className="tab-content project-settings-shell">
            <div className="project-settings-hero">
              <div>
                <p className="project-settings-kicker">Settings</p>
                <h2>Project Control Center</h2>
                <p>Manage project identity, automation behavior, and repository integration from one place.</p>
              </div>
              <div className="project-settings-status">
                <span className={`role-badge role-${currentProject.memberRole}`}>{currentProject.memberRole}</span>
                <span className="project-settings-dot" />
                <span>{currentProject.name}</span>
              </div>
            </div>

            <div className="project-settings-quickstats">
              <div className="project-settings-quickstat">
                <span>Auto Docs</span>
                <strong>{autoGenerateDocs ? 'Enabled' : 'Disabled'}</strong>
              </div>
              <div className="project-settings-quickstat">
                <span>Token</span>
                <strong>{currentProject?.settings?.hasGithubToken ? 'Configured' : 'Missing'}</strong>
              </div>
              <div className="project-settings-quickstat">
                <span>Webhook</span>
                <strong>{currentProject?.settings?.hasWebhook ? 'Active' : 'Not Active'}</strong>
              </div>
            </div>

            <div className="project-settings-grid">
              <section className="settings-section project-settings-card">
                <h3>Project Settings</h3>

              {isEditing ? (
                <div className="edit-form">
                  <div className="form-group">
                    <label htmlFor="name">Project Name</label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      value={editForm.name}
                      onChange={handleEditChange}
                    />
                  </div>
                  <div className="form-group">
                    <label htmlFor="description">Description</label>
                    <textarea
                      id="description"
                      name="description"
                      value={editForm.description}
                      onChange={handleEditChange}
                      rows={4}
                    />
                  </div>
                  <div className="form-group">
                    <label>GitHub URL</label>
                    <input
                      type="url"
                      value={currentProject.githubUrl || ''}
                      disabled
                      className="input-disabled"
                    />
                    <small className="form-hint">GitHub URL cannot be changed after project creation</small>
                  </div>
                  <div className="form-actions">
                    <button className="btn btn-secondary" onClick={() => setIsEditing(false)}>
                      Cancel
                    </button>
                    <button
                      className="btn btn-primary"
                      onClick={handleSaveChanges}
                      disabled={isLoading}
                    >
                      {isLoading ? 'Saving...' : 'Save Changes'}
                    </button>
                  </div>
                </div>
              ) : (
                <div className="settings-display">
                  <div className="setting-item">
                    <label>Project Name</label>
                    <p>{currentProject.name}</p>
                  </div>
                  <div className="setting-item">
                    <label>Description</label>
                    <p>{currentProject.description || 'No description'}</p>
                  </div>
                  <div className="setting-item">
                    <label>GitHub URL</label>
                    <p>{currentProject.githubUrl || 'Not set'}</p>
                  </div>
                  <button className="btn btn-secondary" onClick={() => setIsEditing(true)}>
                    Edit Settings
                  </button>
                </div>
              )}
              </section>

              {/* Documentation Settings */}
              <section className="settings-section project-settings-card">
                <h3>Documentation Settings</h3>

                <div className="setting-item-toggle">
                  <div className="setting-info">
                    <label>Auto-generate Documentation</label>
                    <p className="setting-description">
                      Automatically generate documentation when code changes are pushed to GitHub
                    </p>
                  </div>
                  <label className="toggle-switch">
                    <input
                      type="checkbox"
                      checked={autoGenerateDocs}
                      onChange={handleToggleAutoGenerate}
                      disabled={settingsLoading}
                    />
                    <span className="toggle-slider"></span>
                  </label>
                </div>

                <div className="setting-item-block">
                  <label>GitHub Access Token</label>
                  <p className="setting-description">
                    Required for accessing private repositories and enabling auto-generation features
                  </p>
                  {currentProject?.settings?.hasGithubToken ? (
                    <div className="token-status">
                      <span className="token-set">
                        Token is set
                        {currentProject?.settings?.hasWebhook && (
                          <span className="setting-inline-success">
                            - Webhook active
                          </span>
                        )}
                      </span>
                      <button
                        className="btn btn-secondary btn-sm"
                        onClick={handleClearGithubToken}
                        disabled={settingsLoading}
                      >
                        Clear Token
                      </button>
                    </div>
                  ) : (
                    <div className="token-input-group">
                      <div className="token-input-wrapper">
                        <input
                          type={showGithubToken ? 'text' : 'password'}
                          value={githubToken}
                          onChange={(e) => setGithubToken(e.target.value)}
                          placeholder="ghp_xxxxxxxxxxxx"
                          className="token-input"
                        />
                        <button
                          type="button"
                          className="btn-toggle-visibility"
                          onClick={() => setShowGithubToken(!showGithubToken)}
                        >
                          {showGithubToken ? 'Hide' : 'Show'}
                        </button>
                      </div>
                      <button
                        className="btn btn-primary btn-sm"
                        onClick={handleSaveGithubToken}
                        disabled={settingsLoading || !githubToken.trim()}
                      >
                        {settingsLoading ? 'Saving...' : 'Save Token'}
                      </button>
                    </div>
                  )}
                  {currentProject?.settings?.hasGithubToken && !currentProject?.settings?.hasWebhook && (
                    <p className="setting-note setting-note-warning">
                      Webhook not configured. Token may lack "admin:repo_hook" permission.
                    </p>
                  )}
                </div>

                {/* Manual Documentation Generation */}
                <div className="setting-item-block">
                  <label>Manual Documentation Generation</label>
                  <p className="setting-description">
                    Manually trigger documentation generation for this project. Requires a GitHub access token.
                  </p>
                  {docGenMessage && (
                    <div className={`alert ${docGenMessage.type === 'success' ? 'alert-success' : 'alert-error'} setting-alert`}>
                      {docGenMessage.text}
                    </div>
                  )}
                  <button
                    className="btn btn-primary"
                    onClick={handleTriggerDocGeneration}
                    disabled={docGenLoading || !currentProject?.settings?.hasGithubToken}
                  >
                    {docGenLoading ? 'Generating...' : 'Generate Documentation'}
                  </button>
                  {!currentProject?.settings?.hasGithubToken && (
                    <p className="setting-note setting-note-warning">
                      Please add a GitHub access token above to enable documentation generation.
                    </p>
                  )}
                </div>
              </section>
            </div>

            {/* Danger Zone */}
            {isOwner && (
              <div className="danger-zone">
                <h3>Danger Zone</h3>
                <div className="danger-item">
                  <div>
                    <h4>Delete Project</h4>
                    <p>Once you delete a project, there is no going back. Please be certain.</p>
                  </div>
                  <button
                    className="btn btn-danger"
                    onClick={() => setShowDeleteConfirm(true)}
                  >
                    Delete Project
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Delete Confirmation Modal */}
        {showDeleteConfirm && (
          <div className="modal-overlay" onClick={() => setShowDeleteConfirm(false)}>
            <div className="modal modal-danger" onClick={(e) => e.stopPropagation()}>
              <div className="modal-header">
                <h2>Delete Project</h2>
                <button className="btn-close" onClick={() => setShowDeleteConfirm(false)}>
                  x
                </button>
              </div>
              <p>
                Are you sure you want to delete <strong>{currentProject.name}</strong>? This action
                cannot be undone.
              </p>
              <div className="modal-actions">
                <button
                  className="btn btn-secondary"
                  onClick={() => setShowDeleteConfirm(false)}
                >
                  Cancel
                </button>
                <button className="btn btn-danger" onClick={handleDelete} disabled={isLoading}>
                  {isLoading ? 'Deleting...' : 'Delete Project'}
                </button>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

export default ProjectDetail
