import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import { fetchProjects, createProject, clearError } from '../store/slices/projectsSlice'
import Navbar from '../components/Navbar'
import { Plus, Search, Folder, Github, Globe, Lock, AlertCircle, X, Loader2, FileText, Calendar } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'

const Projects = () => {
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const { projects, isLoading, error } = useAppSelector((state) => state.projects)
  const [showCreateModal, setShowCreateModal] = useState(false)

  // Form State
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    githubUrl: '',
    autoGenerateDocs: false,
    githubAccessToken: '',
  })
  const [showToken, setShowToken] = useState(false)
  const [formError, setFormError] = useState('')

  useEffect(() => {
    dispatch(fetchProjects())
  }, [dispatch])

  useEffect(() => {
    dispatch(clearError())
  }, [dispatch])

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target
    if (type === 'checkbox') {
      const checked = (e.target as HTMLInputElement).checked
      setFormData((prev) => ({ ...prev, [name]: checked }))
    } else {
      setFormData((prev) => ({ ...prev, [name]: value }))
    }
  }

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault()
    setFormError('')

    if (!formData.name.trim()) {
      setFormError('Project name is required')
      return
    }

    if (!formData.githubUrl.trim()) {
      setFormError('GitHub URL is required')
      return
    }

    try {
      new URL(formData.githubUrl)
    } catch {
      setFormError('Please enter a valid GitHub URL')
      return
    }

    const payload = {
      name: formData.name,
      description: formData.description || undefined,
      githubUrl: formData.githubUrl,
      autoGenerateDocs: formData.autoGenerateDocs,
      githubAccessToken: formData.githubAccessToken || undefined,
    }

    const result = await dispatch(createProject(payload))
    if (createProject.fulfilled.match(result)) {
      closeModal()
      navigate(`/projects/${result.payload.id}`)
    }
  }

  const closeModal = () => {
    setShowCreateModal(false)
    setFormData({ name: '', description: '', githubUrl: '', autoGenerateDocs: false, githubAccessToken: '' })
    setShowToken(false)
    setFormError('')
  }

  // Format date helper
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    })
  }

  return (
    <div className="min-h-screen bg-[var(--bg-canvas)] dot-pattern">
      <Navbar title="Projects" />

      <main className="max-w-7xl mx-auto px-6 py-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-bold text-[var(--text-primary)]">Projects</h1>
            <p className="text-[var(--text-secondary)] mt-1">Manage and document your repositories</p>
          </div>

          <button
            onClick={() => setShowCreateModal(true)}
            className="flex items-center gap-2 px-4 py-2 rounded-md bg-[var(--accent-green-emphasis)] hover:bg-[#2ea043] text-white font-medium shadow-sm transition-all"
          >
            <Plus size={18} />
            <span>New Project</span>
          </button>
        </div>

        {error && (
          <div className="mb-6 p-4 rounded-md bg-red-900/20 border border-red-900/50 flex items-center gap-3 text-red-200">
            <AlertCircle size={18} className="shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {isLoading ? (
          <div className="flex justify-center items-center h-64">
            <Loader2 size={32} className="animate-spin text-[var(--accent-blue)]" />
          </div>
        ) : projects.length === 0 ? (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col items-center justify-center p-12 text-center border border-dashed border-[var(--border-muted)] rounded-xl bg-[var(--bg-subtle)]/30"
          >
            <div className="w-16 h-16 rounded-full bg-[var(--bg-subtle)] flex items-center justify-center mb-4">
              <Folder size={32} className="text-[var(--text-secondary)]" />
            </div>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-2">No projects yet</h2>
            <p className="text-[var(--text-secondary)] max-w-sm mb-6">Create your first project to start generating documentation automatically.</p>
            <button
              onClick={() => setShowCreateModal(true)}
              className="btn btn-primary"
            >
              Create Project
            </button>
          </motion.div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {projects.map((project, index) => (
              <motion.div
                key={project.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05 }}
              >
                <Link
                  to={`/projects/${project.id}`}
                  className="block h-full p-6 rounded-xl border border-[var(--border-default)] bg-[var(--bg-default)] hover:border-[var(--accent-blue)] hover:shadow-md transition-all group"
                >
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-3">
                      <div className="p-2 rounded-md bg-[var(--bg-subtle)] text-[var(--text-secondary)] group-hover:text-[var(--accent-blue)] transition-colors">
                        <Folder size={20} />
                      </div>
                      <div>
                        <h3 className="font-semibold text-[var(--text-primary)] group-hover:text-[var(--accent-blue)] transition-colors">{project.name}</h3>
                        <div className="flex items-center gap-2 mt-0.5">
                          <span className={`text-xs px-2 py-0.5 rounded-full border ${project.memberRole === 'owner' || project.memberRole === 'admin' ? 'border-[var(--accent-blue)] text-[var(--accent-blue)] bg-[var(--accent-blue)]/10' : 'border-[var(--border-muted)] text-[var(--text-secondary)]'}`}>
                            {project.memberRole}
                          </span>
                        </div>
                      </div>
                    </div>
                    {project.githubUrl && (
                      <Github size={18} className="text-[var(--text-muted)] hover:text-[var(--text-primary)]" />
                    )}
                  </div>

                  <p className="text-sm text-[var(--text-secondary)] line-clamp-2 mb-6 min-h-[40px]">
                    {project.description || 'No description provided.'}
                  </p>

                  <div className="flex items-center justify-between text-xs text-[var(--text-muted)] pt-4 border-t border-[var(--border-subtle)]">
                    <div className="flex items-center gap-1.5">
                      <Calendar size={14} />
                      <span>{formatDate(project.createdAt)}</span>
                    </div>
                    {project.githubUrl && <div className="flex items-center gap-1">
                      <Github size={12} />
                      <span>Linked</span>
                    </div>}
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        )}

        {/* Create Project Modal */}
        <AnimatePresence>
          {showCreateModal && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="absolute inset-0 bg-black/60 backdrop-blur-sm"
                onClick={closeModal}
              />

              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="relative z-10 w-full max-w-2xl bg-[var(--bg-default)] border border-[var(--border-default)] rounded-xl shadow-2xl overflow-hidden"
              >
                <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--border-default)] bg-[var(--bg-subtle)]/50">
                  <h2 className="text-lg font-semibold text-[var(--text-primary)]">Create New Project</h2>
                  <button onClick={closeModal} className="text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors">
                    <X size={20} />
                  </button>
                </div>

                <div className="p-6 max-h-[80vh] overflow-y-auto">
                  <form onSubmit={handleCreateProject} className="space-y-6">
                    {formError && (
                      <div className="p-3 rounded-md bg-red-900/20 border border-red-900/50 text-red-200 text-sm flex items-center gap-2">
                        <AlertCircle size={16} />
                        {formError}
                      </div>
                    )}

                    {/* Name */}
                    <div>
                      <label htmlFor="name" className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">Project Name <span className="text-red-400">*</span></label>
                      <input
                        type="text"
                        id="name"
                        name="name"
                        value={formData.name}
                        onChange={handleChange}
                        className="w-full px-3 py-2 rounded-md bg-[var(--bg-subtle)] border border-[var(--border-default)] text-[var(--text-primary)] focus:border-[var(--accent-blue)] focus:ring-1 focus:ring-[var(--accent-blue)] focus:outline-none transition-all placeholder-[var(--text-muted)]"
                        placeholder="e.g. backend-api"
                        autoFocus
                      />
                    </div>

                    {/* Description */}
                    <div>
                      <label htmlFor="description" className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">Description</label>
                      <textarea
                        id="description"
                        name="description"
                        value={formData.description}
                        onChange={handleChange}
                        className="w-full px-3 py-2 rounded-md bg-[var(--bg-subtle)] border border-[var(--border-default)] text-[var(--text-primary)] focus:border-[var(--accent-blue)] focus:ring-1 focus:ring-[var(--accent-blue)] focus:outline-none transition-all placeholder-[var(--text-muted)] min-h-[80px]"
                        placeholder="Brief description of your project..."
                      />
                    </div>

                    {/* GitHub URL */}
                    <div>
                      <label htmlFor="githubUrl" className="block text-sm font-medium text-[var(--text-primary)] mb-1.5">GitHub Repository URL <span className="text-red-400">*</span></label>
                      <div className="relative">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                          <Github size={16} className="text-[var(--text-muted)]" />
                        </div>
                        <input
                          type="url"
                          id="githubUrl"
                          name="githubUrl"
                          value={formData.githubUrl}
                          onChange={handleChange}
                          className="w-full pl-10 pr-3 py-2 rounded-md bg-[var(--bg-subtle)] border border-[var(--border-default)] text-[var(--text-primary)] focus:border-[var(--accent-blue)] focus:ring-1 focus:ring-[var(--accent-blue)] focus:outline-none transition-all placeholder-[var(--text-muted)]"
                          placeholder="https://github.com/username/repo"
                        />
                      </div>
                    </div>

                    <div className="border border-[var(--border-muted)] rounded-lg p-4 bg-[var(--bg-subtle)]/30">
                      <h3 className="text-sm font-medium text-[var(--text-primary)] mb-4 flex items-center gap-2">
                        <FileText size={16} className="text-[var(--accent-blue)]" />
                        Documentation Settings
                      </h3>

                      <div className="space-y-4">
                        <label className="flex items-start gap-3 cursor-pointer group">
                          <input
                            type="checkbox"
                            name="autoGenerateDocs"
                            checked={formData.autoGenerateDocs}
                            onChange={handleChange}
                            className="mt-1 w-4 h-4 rounded border-[var(--border-default)] bg-[var(--bg-default)] text-[var(--accent-blue)] focus:ring-[var(--accent-blue)]"
                          />
                          <div>
                            <span className="block text-sm font-medium text-[var(--text-primary)] group-hover:text-[var(--accent-blue)] transition-colors">Auto-generate Documentation</span>
                            <span className="block text-xs text-[var(--text-secondary)] mt-0.5">Automatically listen for pushed code and generate docs</span>
                          </div>
                        </label>

                        {/* Token */}
                        <div className={`transition-all duration-300 ${formData.autoGenerateDocs ? 'opacity-100 max-h-40' : 'opacity-60 max-h-40'}`}>
                          <label htmlFor="githubAccessToken" className="block text-xs font-medium text-[var(--text-secondary)] mb-1.5">
                            GitHub Access Token <span className="font-normal">(required for private repos or auto-gen)</span>
                          </label>
                          <div className="relative">
                            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                              <Lock size={14} className="text-[var(--text-muted)]" />
                            </div>
                            <input
                              type={showToken ? 'text' : 'password'}
                              id="githubAccessToken"
                              name="githubAccessToken"
                              value={formData.githubAccessToken}
                              onChange={handleChange}
                              className="w-full pl-9 pr-16 py-2 rounded-md bg-[var(--bg-default)] border border-[var(--border-default)] text-[var(--text-primary)] text-sm focus:border-[var(--accent-blue)] focus:ring-1 focus:ring-[var(--accent-blue)] focus:outline-none transition-all placeholder-[var(--text-muted)] font-mono"
                              placeholder="ghp_..."
                            />
                            <button
                              type="button"
                              onClick={() => setShowToken(!showToken)}
                              className="absolute inset-y-0 right-0 px-3 text-xs text-[var(--accent-blue)] hover:text-[var(--text-primary)] transition-colors font-medium"
                            >
                              {showToken ? 'Hide' : 'Show'}
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center justify-end gap-3 pt-4 border-t border-[var(--border-default)]">
                      <button
                        type="button"
                        onClick={closeModal}
                        className="px-4 py-2 rounded-md border border-[var(--border-default)] text-[var(--text-secondary)] hover:bg-[var(--bg-subtle)] hover:text-[var(--text-primary)] text-sm font-medium transition-colors"
                      >
                        Cancel
                      </button>
                      <button
                        type="submit"
                        disabled={isLoading}
                        className="flex items-center gap-2 px-4 py-2 rounded-md bg-[var(--accent-green-emphasis)] hover:bg-[#2ea043] text-white text-sm font-medium shadow-sm transition-all disabled:opacity-70 disabled:cursor-not-allowed"
                      >
                        {isLoading && <Loader2 size={14} className="animate-spin" />}
                        {isLoading ? 'Creating...' : 'Create Project'}
                      </button>
                    </div>
                  </form>
                </div>
              </motion.div>
            </div>
          )}
        </AnimatePresence>
      </main>
    </div>
  )
}

export default Projects
