import json
import os

def build_pr_comment(report, docs_path="artifacts/docs"):
    severity = report["analysis_summary"]["highest_severity"]
    breaking = report["analysis_summary"]["breaking_changes_detected"]

    files = []
    for root, _, filenames in os.walk(docs_path):
        for f in filenames:
            files.append(os.path.relpath(os.path.join(root, f), docs_path))

    files_md = "\n".join([f"- `{f}`" for f in files])

    return f"""
## 📚 Documentation Update Summary (EPIC-2)

### 🔍 Change Context
- Severity: **{severity}**
- Breaking Changes: {'✅ Yes' if breaking else '❌ No'}

### 📄 Generated Files
{files_md}

> Auto-generated by EPIC-2 documentation pipeline.
"""