import argparse
import os
import sys
import glob
from epic4.config import config
from epic4.utils import logger
from epic4.summary import generate_summary
from epic4.github_client import GitHubClient
from epic4.storage_client import StorageClient

def main():
    parser = argparse.ArgumentParser(description="Epic-4 CI Automation")
    parser.add_argument("--impact", default=config.IMPACT_REPORT_PATH, help="Path to impact report")
    parser.add_argument("--drift", default=config.DRIFT_REPORT_PATH, help="Path to drift report")
    parser.add_argument("--docs", default=config.DOCS_DIR, help="Path to docs directory")
    parser.add_argument("--commit", default=config.COMMIT_SHA, help="Commit SHA")

    args = parser.parse_args()

    # 1. Validation
    try:
        config.validate()
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        sys.exit(1)

    logger.info(f"Starting Epic-4 execution for commit {args.commit}")

    # 2. Download documentation artifacts from cloud storage if configured
    if config.DOCS_BUCKET_PATH:
        logger.info(f"Downloading docs from cloud storage: {config.DOCS_BUCKET_PATH}")
        storage_client = StorageClient()
        success = storage_client.download_artifacts(config.DOCS_BUCKET_PATH, args.docs)
        if not success:
            logger.warning("Failed to download from cloud storage, continuing with local files")
    else:
        logger.info("No cloud storage path configured, using local docs")

    # 3. Generate Summary with fault tolerance
    try:
        summary_path = generate_summary(args.impact, args.drift, args.commit, config.SUMMARIES_DIR)
        with open(summary_path, 'r') as f:
            summary_content = f.read()
    except Exception as e:
        logger.error(f"Failed to generate summary: {e}")
        # Create error summary for partial artifact preservation
        summary_path = os.path.join(config.SUMMARIES_DIR, "summary.md")
        os.makedirs(config.SUMMARIES_DIR, exist_ok=True)
        summary_content = f"""# Change Summary - Generation Failed

**Commit SHA:** `{args.commit}`
**Status:** ERROR

## Error
Summary generation encountered an error:
```
{str(e)}
```

This is a degraded artifact. Please check the impact and drift reports manually.

---
*Generated by Epic-4 Automation*
"""
        with open(summary_path, 'w') as f:
            f.write(summary_content)
        logger.info(f"Created error summary at {summary_path}")

    # 4. Collect Files
    files_to_commit = []

    # Docs
    if os.path.isdir(args.docs):
        for root, dirs, files in os.walk(args.docs):
            for file in files:
                files_to_commit.append(os.path.join(root, file))

    # Summary
    files_to_commit.append(summary_path)

    logger.info(f"Files to commit: {len(files_to_commit)}")

    # 4. Git Operations & PR
    gh = GitHubClient(config.REPO_OWNER, config.REPO_NAME, config.GITHUB_TOKEN)

    branch_name = f"auto/docs/{args.commit}"

    try:
        # Push artifacts
        gh.checkout_and_push_files(
            branch_name=branch_name,
            files_to_commit=files_to_commit,
            message=f"Auto-generated docs and summary for {args.commit}"
        )

        # Create/Update PR
        pr_number = gh.ensure_pr(
            head_branch=branch_name,
            base_branch=config.TARGET_BRANCH,
            title="Automated Documentation & Summary Update",
            body=summary_content,
            labels=["auto-generated-docs"]
        )

        logger.info(f"Successfully processed PR #{pr_number}")

    except Exception as e:
        logger.error(f"Automation failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
