import json
import os
from typing import Dict, Any, List
from epic4.config import config
from epic4.utils import logger

class SummaryGenerator:
    def __init__(self, impact_report_path: str, drift_report_path: str, commit_sha: str, output_dir: str):
        self.impact_report_path = impact_report_path
        self.drift_report_path = drift_report_path
        self.commit_sha = commit_sha
        self.output_dir = output_dir

    def load_json(self, path: str) -> Dict[str, Any]:
        if not os.path.exists(path):
            logger.warning(f"File not found: {path}. Returning empty dict.")
            return {}
        try:
            with open(path, 'r') as f:
                return json.load(f)
        except json.JSONDecodeError as e:
            logger.error(f"Failed to decode JSON from {path}: {e}")
            return {}

    def generate(self) -> str:
        impact = self.load_json(self.impact_report_path)
        drift = self.load_json(self.drift_report_path)

        severity = impact.get("severity", "UNKNOWN")
        changed_files = impact.get("changed_files", [])
        affected_symbols = impact.get("affected_symbols", [])
        drift_issues = drift.get("issues", [])

        summary_md = self._render_template(severity, changed_files, affected_symbols, drift_issues)

        # Contract-mandated filename for Epic-5 dashboard integration
        output_filename = "summary.md"
        output_path = os.path.join(self.output_dir, output_filename)

        os.makedirs(self.output_dir, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(summary_md)

        logger.info(f"Summary generated at {output_path}")
        return output_path

    def _render_template(self, severity: str, changed_files: List[str], affected_symbols: List[str], drift_issues: List[Dict]) -> str:
        # Deterministic sorting
        changed_files.sort()
        affected_symbols.sort()
        # Sort drift issues by severity and description for deterministic output
        if drift_issues and isinstance(drift_issues[0], dict):
            drift_issues.sort(key=lambda x: (x.get('severity', ''), x.get('description', str(x))))

        template = f"""# Change Summary

**Commit SHA:** `{self.commit_sha}`
**Severity:** {severity}

## Impact Analysis
### Changed Modules/Files ({len(changed_files)})
"""
        if changed_files:
            for file in changed_files:
                template += f"- `{file}`\n"
        else:
            template += "- No changed files detected.\n"

        template += f"\n### Affected Symbols/Functions ({len(affected_symbols)})\n"

        if affected_symbols:
            for symbol in affected_symbols:
                template += f"- `{symbol}`\n"
        else:
            template += "- No specific symbols identified as affected.\n"

        template += f"\n## Drift Report ({len(drift_issues)} Issues)\n"
        if drift_issues:
            for issue in drift_issues:
                # assuming issue structure, falling back to string representation
                desc = issue.get("description", str(issue))
                severity = issue.get("severity", "")
                template += f"- [{severity}] {desc}\n"
        else:
            template += "- No drift issues detected.\n"

        template += "\n---\n*Generated by Epic-4 Automation*\n"

        return template

def generate_summary(impact_path, drift_path, commit_sha, output_dir):
    generator = SummaryGenerator(impact_path, drift_path, commit_sha, output_dir)
    return generator.generate()
